### PR TITLE
Combined Rule

### LINKED ISSUE #64: Combined Rule
After reviewing https://github.com/skeeto/boids-js I came to conclusion that our implementation has several major flaws right now:

- [x] Wrap both position of the boid.
- [x] Average angle is broken. See https://en.wikipedia.org/wiki/Mean_of_circular_quantities
- [x] Alignment and cohesion rule are applied simultaneously by using mean angle of their targets
- [x] Alignment rule has roughly 3/4 influence over the cohesion rule
- [x] Separation rule has the highest priority and override any other rule

Should fix #20

### PR DESCRIPTION
**Pull request by rexim**
Close #64

### CODE REVIEW

File: src/Boids.hs [hunk 1]
```diff
@@ -165,27 +206,33 @@ resetBoidsSteer :: [Boid] -> [Boid]
...
                                        , guideY + guideSpeed * deltaTime)
 
 randomBoid :: IO Boid
-randomBoid = do x <- randomRIO (-1200.0, 1200.0)
-                y <- randomRIO (-1200.0, 1200.0)
+randomBoid = do x <- randomRIO (-worldSize, worldSize)
+                y <- randomRIO (-worldSize, worldSize)
                 heading <- randomRIO (0.0, 2 * pi)
-                steer <- randomRIO (0.0, 2 * pi)
+                -- steer <- randomRIO (0.0, 2 * pi)
```
Comment (rexim) [inline src/Boids.hs]: Uncomment back

File: src/Boids.hs [hunk 2]
```diff
@@ -165,27 +206,33 @@ resetBoidsSteer :: [Boid] -> [Boid]
...
                 return $ Boid { boidPosition = (x, y)
                               , boidHeading = heading
-                              , boidSteer = steer
+                              , boidSteer = 0.0
```
Comment (rexim) [inline src/Boids.hs]: Revert this
